version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/cenv-vscode"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/packages/cenv-rs"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/packages/cenv-go"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/packages/cenv-python"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
